name: 'openbuild_dbt'
version: '1.0.0'

profile: 'openbuild_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests_dbt"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  openbuild_dbt:
    staging:
      +materialized: view
      +schema: silver
    marts:
      +materialized: table
      +schema: gold
